Repository ontoportal-lirmm/bioportal_web_ui, pull requests merged in 2023-02, with the labels that each got.

#156 Feature: Update feedback design
  app/assets/images/check.svg
  app/assets/images/green-check.svg
  app/assets/images/red-warning.svg
  app/assets/stylesheets/application.css.scss.erb
  app/assets/stylesheets/card_message.scss
  app/assets/stylesheets/feedback.scss
  app/components/card_message_component.rb
  app/components/card_message_component/card_message_component.html.haml
  app/controllers/home_controller.rb
  app/helpers/application_helper.rb
  app/mailers/notifier.rb
  app/views/home/feedback.html.haml
  app/views/home/feedback/feedback.html.haml
  app/views/home/feedback/feedback_complete.html.haml
  app/views/home/feedback_complete.html.erb
  app/views/notifier/feedback.html.erb
Labels: enhancement

#166 Feature: Extract card message component
  app/assets/images/green-check.svg
  app/assets/images/red-warning.svg
  app/assets/stylesheets/application.css.scss.erb
  app/assets/stylesheets/card_message.scss
  app/components/card_message_component.rb
  app/components/card_message_component/card_message_component.html.haml
Labels: enhancement

#197 Fix: Password recovery success message
  app/views/login/lost_password_success.html.haml
Labels: bug

#198 Feature: Add Newrelic configuration file
  .gitignore
  Gemfile.lock
  config/newrelic.yml
Labels: documentation, enhancement

#181 Feature: Extract chips component
  app/assets/stylesheets/application.css.scss.erb
  app/assets/stylesheets/components/card_message.scss
  app/assets/stylesheets/components/chips.scss
  app/assets/stylesheets/components/index.scss
  app/components/chips_component.rb
  app/components/chips_component/chips_component.html.haml
Labels: enhancement

#144 Feature: Update register template
  app/assets/images/arrow-back.svg
  app/assets/images/github-icon.svg
  app/assets/images/orcid.svg
  app/assets/stylesheets/application.css.scss.erb
  app/assets/stylesheets/register.scss
  app/controllers/users_controller.rb
  app/views/users/_form.html.haml
  app/views/users/new.html.haml
Labels: enhancement

#205 Fix: Production colors issues
  app/assets/images/check.svg
  app/assets/stylesheets/components/chips.scss
  app/assets/stylesheets/feedback.scss
  app/assets/stylesheets/register.scss
  app/assets/stylesheets/theme-variables.scss.erb
  app/components/chips_component/chips_component.html.haml
Labels: bug
