Repository ontoportal-lirmm/bioportal_web_ui, pull requests merged in 2023-08, with the labels that each got.

#297 Feature: Add tabs component
  app/assets/images/icons/calendar.svg
  app/assets/images/icons/list-tree.svg
  app/assets/images/icons/list.svg
  app/assets/images/list-tree.svg
  app/assets/stylesheets/components/index.scss
  app/assets/stylesheets/components/outline_tabs_container.scss
  app/assets/stylesheets/components/pill_tabs_container.scss
  app/assets/stylesheets/components/tabs_container.scss
  app/assets/stylesheets/concepts.scss
  app/assets/stylesheets/ontologies.scss
  app/components/rounded_button_component.rb
  app/components/rounded_button_component/rounded_button_component.html.haml
  app/components/tab_item_component.rb
  app/components/tabs_container_component.rb
  app/components/tabs_container_component/tabs_container_component.html.haml
  app/components/tabs_container_component/tabs_container_component_controller.js
  app/helpers/ontologies_helper.rb
  app/javascript/component_controllers/index.js
  app/javascript/controllers/ontology_viewer_tabs_controller.js
  app/views/admin/index.html.haml
  app/views/concepts/_show.html.haml
  app/views/layouts/_ontology_viewer.html.haml
  app/views/ontologies/concepts_browsers/_concepts_browser.html.haml
  app/views/ontologies/sections/visualize.html.haml
  test/components/previews/layout/tabs_container_component_preview.rb
Labels: enhancement

#306 Feature: Add circle progress bar component (style, JS, code and preview)
  Gemfile.lock
  app/assets/stylesheets/components/circle_progress_bar.scss
  app/assets/stylesheets/components/index.scss
  app/components/circle_progress_bar_component.rb
  app/components/circle_progress_bar_component/circle_progress_bar_component.html.haml
  app/components/circle_progress_bar_component/circle_progress_bar_component_controller.js
  app/javascript/component_controllers/index.js
  test/components/previews/display/circle_progress_bar_component_preview.rb
Labels: enhancement

#247 Feature: Update AgroPortal primary color
  app/assets/stylesheets/theme-variables.scss.erb
  app/assets/stylesheets/themes/agroportal/main.scss
  app/assets/stylesheets/themes/ontoportal/main.scss
  app/assets/stylesheets/themes/stageportal/main.scss
Labels: enhancement

#278 Feature: Add agent model components and integration
  Gemfile
  app/assets/stylesheets/agents.scss
  app/assets/stylesheets/application.css.scss.erb
  app/assets/stylesheets/components/index.scss
  app/components/agent_search_input_component.rb
  app/components/agent_search_input_component/agent_search_input_component.html.haml
  app/components/nested_agent_search_input_component.rb
  app/components/nested_agent_search_input_component/nested_agent_search_input_component.html.haml
  app/components/search_input_component.rb
  app/components/select_input_component.rb
  app/components/text_field_component/text_field_component.html.haml
  app/controllers/agents_controller.rb
  app/controllers/concerns/submission_updater.rb
  app/controllers/ontologies_controller.rb
  app/controllers/submissions_controller.rb
  app/helpers/admin_helper.rb
  app/helpers/agent_helper.rb
  app/helpers/application_helper.rb
  app/helpers/ontologies_helper.rb
  app/helpers/submissions_helper.rb
  app/views/admin/index.html.haml
  app/views/agents/_agent_show.html.haml
  app/views/agents/_form.html.haml
  app/views/agents/_show_line.html.haml
  app/views/agents/_table_list.html.haml
  app/views/agents/edit.html.haml
  app/views/agents/index.html.haml
  app/views/agents/new.html.haml
  app/views/agents/show.html.haml
  app/views/ontologies_metadata_curator/_attribute_inline.html.haml
  app/views/submissions/_form.html.haml
  app/views/submissions/_form_content.html.haml
  app/views/submissions/edit.html.haml
  app/views/submissions/new.html.haml
  config/routes.rb
Labels: enhancement

#318 Feature: Add multi provider Authentication
  Gemfile
  Gemfile.lock
  app/assets/images/icons/github.svg
  app/assets/images/icons/google.svg
  app/assets/images/icons/keycloak.svg
  app/assets/images/icons/orcid.svg
  app/assets/stylesheets/login.scss
  app/controllers/login_controller.rb
  app/helpers/application_helper.rb
  app/views/login/index.html.haml
  config/bioportal_config_env.rb.sample
  config/initializers/omniauth.rb
  config/routes.rb
Labels: documentation, enhancement

#322 Feature: Update ontology details header design
  app/assets/images/edit.svg
  app/assets/stylesheets/application.css.scss.erb
  app/assets/stylesheets/components/chip_button.scss
  app/assets/stylesheets/nav_bar.scss
  app/assets/stylesheets/ontology_details_header.scss
  app/components/chip_button_component.rb
  app/components/chip_button_component/chip_button_component.html.haml
  app/components/label_link_component.rb
  app/components/rounded_button_component.rb
  app/controllers/ontologies_controller.rb
  app/helpers/application_helper.rb
  app/helpers/ontologies_helper.rb
  app/views/layouts/_ontology_viewer.html.haml
  app/views/layouts/ontology_viewer/_header.html.haml
  app/views/ontologies/sections/_licenses.html.haml
  config/routes.rb
Labels: enhancement

#329 Fix: Github provider authentification code issue
  app/helpers/application_helper.rb
Labels: bug

#314 Feature: Add buttons components to lookbook
  Gemfile.lock
  app/assets/stylesheets/bioportal.scss
  app/assets/stylesheets/components/index.scss
  app/assets/stylesheets/components/regular_button.scss
  app/assets/stylesheets/login.scss
  app/assets/stylesheets/register.scss
  app/components/buttons/regular_button_component.rb
  app/components/buttons/regular_button_component/regular_button_component.html.haml
  app/components/display/button_loader_component.rb
  app/views/login/index.html.haml
  app/views/users/_form.html.haml
  test/components/previews/buttons/chip_button_component_preview.rb
  test/components/previews/buttons/ontology_subscribe_button_component_preview.rb
  test/components/previews/buttons/pill_button_component_preview.rb
  test/components/previews/buttons/regular_button_component_preview.rb
  test/components/previews/buttons/rounded_button_component_preview.rb
Labels: enhancement

#328 Feature: Add progress pages component
  app/assets/images/icons/arrow-left.svg
  app/assets/images/icons/white-check.svg
  app/assets/stylesheets/bioportal.scss
  app/assets/stylesheets/components/index.scss
  app/assets/stylesheets/components/progress_pages.scss
  app/components/layout/progress_pages_component.rb
  app/components/layout/progress_pages_component/progress_pages_component.html.haml
  app/components/layout/progress_pages_component/progress_pages_component_controller.js
  app/javascript/component_controllers/index.js
  test/components/previews/layout/progress_pages_component_preview.rb
Labels: enhancement

#330 Feature: add alert component
  app/assets/images/danger.svg
  app/assets/images/info.svg
  app/assets/images/success.svg
  app/assets/images/warning.svg
  app/assets/images/x.svg
  app/assets/stylesheets/components/alert.scss
  app/assets/stylesheets/components/index.scss
  app/components/alert_message_component.rb
  app/components/alert_message_component/alert_message_component.html.haml
  app/components/display/alert_component.rb
  app/components/display/alert_component/alert_component.html.haml
  app/components/display/alert_component/alert_component_controller.js
  app/components/infinite_scroll_component/infinite_scroll_component.html.haml
  app/components/turbo_frame_component/turbo_frame_component.html.haml
  app/helpers/collections_helper.rb
  app/helpers/schemes_helper.rb
  app/helpers/turbo_helper.rb
  app/javascript/component_controllers/index.js
  app/views/concepts/_details.html.haml
  app/views/mappings/bulk_loader/_loaded_mappings.html.haml
  app/views/ontologies_metadata_curator/_attribute_inline.html.haml
  app/views/ontologies_metadata_curator/_form_edit.html.haml
  spec/components/alert_message_component_spec.rb
  test/components/previews/alert_message_component_preview.rb
  test/components/previews/display/alert_component_preview.rb
Labels: enhancement

#292 Feature: Implement the new upload ontology form
  app/assets/images/arrow-right.svg
  app/assets/images/json.svg
  app/assets/images/white-check.svg
  app/assets/stylesheets/application.css.scss.erb
  app/assets/stylesheets/components/chips.scss
  app/assets/stylesheets/components/input_field.scss
  app/assets/stylesheets/components/primary_button.scss
  app/assets/stylesheets/components/regular_button.scss
  app/assets/stylesheets/upload_ontology.scss
  app/components/buttons/primary_button_component/primary_button_component.html.haml
  app/components/buttons/regular_button_component.rb
  app/components/chips_component/chips_component.html.haml
  app/components/input/date_component.rb
  app/components/input/input_field_component.rb
  app/components/input/input_field_component/input_field_component.html.haml
  app/components/input/text_input_component.rb
  app/components/nested_form_inputs_component/nested_form_inputs_component.html.haml
  app/components/select_input_component.rb
  app/controllers/concerns/ontology_updater.rb
  app/controllers/concerns/submission_updater.rb
  app/controllers/ontologies_controller.rb
  app/controllers/submissions_controller.rb
  app/helpers/application_helper.rb
  app/helpers/inputs_helper.rb
  app/helpers/ontologies_helper.rb
  app/helpers/submissions_helper.rb
  app/javascript/controllers/tom_select_controller.js
  app/views/layouts/_topnav.html.haml
  app/views/layouts/component_preview.html.erb
  app/views/login/index.html.haml
  app/views/ontologies/_form.html.haml
  app/views/ontologies/_submission_location_form.html.haml
  app/views/ontologies/edit.html.haml
  app/views/ontologies/new.html.haml
  app/views/shared/_ontology_picker_single.html.erb
  app/views/submissions/new.html.haml
Labels: enhancement
