Repository ontoportal-lirmm/bioportal_web_ui, pull requests merged in 2024-11, with the labels that each got.

#822 Fix: Remove ontolobrigde code and some Jquery code
  .env.sample
  app/assets/javascripts/bp_ontolobridge.js
  app/assets/stylesheets/application.css.scss.erb
  app/assets/stylesheets/ontolobridge.scss
  app/controllers/concepts_controller.rb
  app/controllers/ontolobridge_controller.rb
  app/controllers/ontologies_controller.rb
  app/helpers/application_helper.rb
  app/javascript/controllers/class_search_auto_complete_controller.js
  app/views/concepts/_request_term.html.haml
  app/views/layouts/_header.html.erb
  app/views/layouts/_ontology_viewer.html.haml
  app/views/layouts/appliance.html.haml
  app/views/layouts/component_preview.html.erb
  app/views/layouts/component_preview_not_centred.html.erb
  app/views/layouts/popup.html.erb
  app/views/layouts/tool.html.haml
  app/views/ontologies/sections/visualize.html.haml
  config/application.rb
  config/bioportal_config_env.rb.sample
  config/locales/en.yml
  config/locales/fr.yml
  config/routes.rb
  db/schema.rb
Labels: enhancement

#746 Fix: if analytics not enabled use the metrics to display home page visits
  app/controllers/home_controller.rb
  app/views/home/index.html.haml
  config/locales/en.yml
  config/locales/fr.yml
Labels: bug, enhancement

#844 Fix: tests after merging home page bubbles if no analytics enabled
  app/controllers/home_controller.rb
  app/helpers/home_helper.rb
Labels: bug

#843 Fix: migrate notes table to use DataTable component fully and remove archived filter
  app/assets/javascripts/application.js
  app/assets/javascripts/bp_notes.js
  app/views/notes/_notes.html.haml
Labels: enhancement

#846 Fix: Notes buttons showing, some properties details, and no collection selection showing content missing or an error alert
  app/controllers/collections_controller.rb
  app/helpers/application_helper.rb
  app/helpers/components_helper.rb
  app/helpers/ontologies_helper.rb
  app/views/concepts/_list.html.haml
  app/views/notes/_new_comment.html.haml
  app/views/notes/_new_proposal.html.haml
Labels: bug, enhancement

#842 Fix: notes and zombie mappings class label fetching and optimize concept mapping table API calls
  app/controllers/concepts_controller.rb
  app/helpers/mappings_helper.rb
  app/views/notes/_note_line.html.haml
Labels: bug, enhancement

#852 Fix: Add a star for the required fields in the upload form
  app/helpers/submission_inputs_helper.rb
  app/views/ontologies/_submission_location_form.html.haml
  app/views/ontologies/new.html.haml
Labels: bug, enhancement

#857 Fix: users edition and login_as with the `@` symbol in there usernames
  app/controllers/application_controller.rb
  app/controllers/users_controller.rb
  config/routes.rb
Labels: bug

#855 Fix: `Tree View` Prevent word break for the elements
  app/assets/stylesheets/components/tree_view.scss
Labels: bug

#854 Fix: Federation portal button link
  app/components/federated_portal_button_component.rb
  app/components/federated_portal_button_component/federated_portal_button_component.html.haml
  app/helpers/federation_helper.rb
Labels: bug

#858 Fix: Taxonomy empty list
  app/assets/stylesheets/taxonomy.scss
  app/controllers/taxonomy_controller.rb
  app/helpers/components_helper.rb
  app/views/taxonomy/_taxonomies.html.haml
  app/views/taxonomy/index.html.haml
  config/locales/en.yml
  config/locales/fr.yml
Labels: bug, enhancement

#871 Fix: Change portal language
  app/controllers/application_controller.rb
Labels: bug

#870 Fix: `Federated search/browse` results count by portal
  app/helpers/federation_helper.rb
Labels: enhancement
