Repository ontoportal-lirmm/bioportal_web_ui, pull requests merged in 2024-01, with the labels that each got.

#420 Feature: Add icons to display orcid, and affiliations in agent tooltip
  app/assets/images/icons/ror.svg
  app/assets/stylesheets/agent_tooltip.scss
  app/helpers/agent_helper.rb
Labels: enhancement

#436 Fix: Search page issues
  app/components/display/search_result_component.rb
  app/components/display/search_result_component/search_result_component.html.haml
  app/controllers/search_controller.rb
  app/views/search/index.html.haml
  config/locales/de.yml
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/it.yml
Labels: bug

#417 Fix: home page issues
  Gemfile.lock
  app/assets/images/icons/arrow-curved-up.svg
  app/assets/stylesheets/components/regular_button.scss
  app/assets/stylesheets/home.scss
  app/components/search_input_component/search_input_component_controller.js
  app/controllers/application_controller.rb
  app/helpers/home_helper.rb
  app/javascript/controllers/history_controller.js
  app/javascript/controllers/index.js
  app/javascript/controllers/sample_text_controller.js
  app/views/home/index.html.haml
  config/bioportal_config_env.rb.sample
  config/locales/de.yml
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/it.yml
Labels: enhancement

#433 Feature: Update recommender page design
  app/assets/images/icons/cite.svg
  app/assets/javascripts/application.js
  app/assets/javascripts/bp_recommender.js
  app/assets/stylesheets/components/index.scss
  app/assets/stylesheets/components/progress_bar.scss
  app/assets/stylesheets/components/radio.scss
  app/assets/stylesheets/components/table.scss
  app/assets/stylesheets/recommender.scss
  app/components/buttons/regular_button_component.rb
  app/components/display/progress_bar_component.rb
  app/components/input/input_field_component.rb
  app/components/input/input_field_component/input_field_component.html.haml
  app/components/input/number_component.rb
  app/components/input/radio_chip_component.rb
  app/components/input/radio_chip_component/radio_chip_component.html.haml
  app/components/input/radio_chip_component/radio_chip_component_controller.js
  app/components/table_component.rb
  app/components/table_component/table_component.html.haml
  app/components/table_component/table_component_controller.js
  app/controllers/home_controller.rb
  app/controllers/recommender_controller.rb
  app/helpers/application_helper.rb
  app/javascript/component_controllers/index.js
  app/javascript/controllers/index.js
  app/javascript/controllers/recommender_controller.js
  app/views/home/index.html.haml
  app/views/recommender/index.html.haml
  config/bioportal_config_test.rb
  config/locales/en.yml
  config/locales/fr.yml
  package.json
  test/components/previews/input/input_field_component_preview.rb
  yarn.lock
Labels: enhancement

#464 fix: escape user id and include all attribute when fetched in the user paths
  Gemfile
  Gemfile.lock
  app/controllers/login_controller.rb
  app/controllers/users_controller.rb
  config/bioportal_config_env.rb.sample
  config/initializers/bugsnag.rb
Labels: bug

#466 Fix: Add slider component to recommender page
  app/assets/stylesheets/components/index.scss
  app/assets/stylesheets/components/range_slider.scss
  app/assets/stylesheets/recommender.scss
  app/components/input/range_slider_component.rb
  app/components/input/range_slider_component/range_slider_component.html.haml
  app/components/input/range_slider_component/range_slider_component_controller.js
  app/controllers/recommender_controller.rb
  app/javascript/component_controllers/index.js
  app/javascript/controllers/recommender_controller.js
  app/views/recommender/index.html.haml
Labels: bug, enhancement

#471 Feature: Add keywords tooltip in Recommender page
  app/views/recommender/index.html.haml
Labels: enhancement
