Repository ontoportal-lirmm/bioportal_web_ui, pull requests merged in 2024-07, with the labels that each got.

#695 Fix: docker compose to make tests work
  docker-compose.yml
Labels: bug

#684 Feature: rewrite condition in redirection rules
  app/controllers/ontologies_redirection_controller.rb
Labels: enhancement

#685 Fix: Ontologies custom set not working
  app/assets/stylesheets/account.scss
  app/controllers/home_controller.rb
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/views/users/show.html.haml
  config/routes.rb
  test/integration/login_flows_test.rb
  test/system/login_flows_test.rb
Labels: bug

#681 Fix: subscribe button issues
  app/assets/stylesheets/components/pill_button.scss
  app/assets/stylesheets/fair_assement.scss
  app/components/ontology_subscribe_button_component.rb
  app/components/ontology_subscribe_button_component/ontology_subscribe_button_component.html.haml
  app/components/ontology_subscribe_button_component/ontology_subscribe_button_component_controller.js
  app/controllers/ontologies_controller.rb
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  config/locales/en.yml
Labels: bug

#717 Feature: add response time calculation in check resolvability tool
  app/components/url_resolvability_component.rb
  app/helpers/check_resolvability_helper.rb
  app/views/check_resolvability/index.html.haml
Labels: enhancement

#720 Fix: Lost view of value on submssion creation or editition
  app/helpers/submission_inputs_helper.rb
  docker-compose.yml
Labels: bug

#716 Feature: add ontology viewOf the the summary page relation network
  app/controllers/ontologies_controller.rb
Labels: enhancement

#719 Feature: remove subject values from the project and usage block in summary page
  app/controllers/ontologies_controller.rb
Labels: enhancement

#702 Feature: Add cookie banner
  app/assets/stylesheets/bioportal.scss
  app/controllers/home_controller.rb
  app/helpers/application_helper.rb
  app/views/home/cookies.html.haml
  app/views/layouts/_header.html.erb
  app/views/layouts/appliance.html.haml
  config/locales/en.yml
  config/locales/fr.yml
  config/routes.rb
Labels: enhancement

#713 Fix: update summary page categories display to show acronym with tooltip
  app/helpers/ontologies_helper.rb
  app/views/ontologies/sections/metadata/_ontology_description_section.html.haml
  test/system/submission_flows_test.rb
Labels: enhancement

#703 Feature: Enhance agents search input component
  app/assets/stylesheets/components/search_input.scss
  app/components/agent_search_input_component/agent_search_input_component.html.haml
  app/components/search_input_component.rb
  app/components/search_input_component/search_input_component.html.haml
  app/components/search_input_component/search_input_component_controller.js
  app/controllers/agents_controller.rb
Labels: bug, enhancement
