Repository ontoportal-lirmm/bioportal_web_ui, pull requests merged in 2024-06, with the labels that each got.

#651 Fix: change URL to URI in check resolvability
  config/locales/en.yml
  config/locales/fr.yml
Labels: enhancement

#657 Fix: Multiple highlighted terms in the date view
  app/helpers/concepts_helper.rb
Labels: bug

#658 Feature: Clean no more used gems and code
  Gemfile
  Gemfile.lock
  app/controllers/ajax_proxy_controller.rb
  app/controllers/annotator_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concepts_controller.rb
  app/controllers/notes_controller.rb
  app/controllers/ontologies_controller.rb
  app/controllers/search_controller.rb
  app/helpers/application_helper.rb
  app/helpers/components_helper.rb
  app/helpers/home_helper.rb
  app/models/bpid_resolver.rb
  app/views/mappings/_form.html.haml
  config/bioportal_config_test.rb
  config/initializers/cube_reporter.rb
  config/initializers/miniprofiler.rb
  config/routes.rb
  lib/resolver/acronym_from_virtual.rb
  lib/resolver/virtual_from_acronym.rb
  lib/resolver/virtual_from_version.rb
Labels: enhancement

#663 Fix: handle the case reset_agents in edit submissions error state are already Agents
  app/controllers/concerns/ontology_updater.rb
Labels: bug

#665 Feature: Add issues and requests link to the footer and feedback form
  app/views/home/feedback/feedback.html.haml
  config/bioportal_config_env.rb.sample
  config/locales/en.yml
  config/locales/fr.yml
Labels: enhancement

#664 Fix: the width of the ontlogy viewer left block of classes, instances, ...
  app/assets/stylesheets/ontologies.scss
Labels: bug

#669 Fix: submissions properties selector labels and include ontologies properties
  app/helpers/submission_inputs_helper.rb
  app/helpers/submissions_helper.rb
  lib/tasks/schema.rake
Labels: enhancement

#673 Fix: Redirect to the login page when accessing private ontology while being not authenticated.
  app/assets/stylesheets/login.scss
  app/assets/stylesheets/ontologies.scss
  app/controllers/ontologies_controller.rb
  app/helpers/ontologies_helper.rb
  app/javascript/controllers/content_finder_controller.js
  app/javascript/controllers/label_ajax_controller.js
  app/javascript/controllers/mappings_visualization_controller.js
  app/views/instances/_details.html.haml
  app/views/login/index.html.haml
  config/environment.rb
  config/locales/en.yml
  config/locales/fr.yml
Labels: bug, enhancement

#683 Fix: Json file extention in export metadata summary page
  app/components/display/rdf_highlighter_component/rdf_highlighter_component_controller.js
Labels: bug
